name: pedsum
channels:
  - conda-forge
dependencies:
  - python>=3.13
  - numpy
  - scipy
  - pandas
  - pyyaml
  - pigz
  - ruff
  - pip
  - pip:
      - pedigree-graph @ git+https://github.com/rwaples/pedigree-graph.git@v0.5.0
